function showRecipe() {
    const recipeOutput = document.getElementById('recipe');
    const selectedFood = document.getElementById('food-options').value;
    let recipeText = '';

    if (selectedFood === 'Dosa') {
        recipeText = 'Dosa is a traditional South Indian dish made from a fermented batter of rice and urad dal (split black gram). To prepare it, start by soaking 2 cups of rice and 1 cup of urad dal separately for 4-6 hours. After soaking, grind them together to form a smooth batter, adding water as needed. Allow the batter to ferment overnight or for 8-12 hours in a warm place until it doubles in size. Once fermented, mix the batter well and add salt to taste. Heat a non-stick pan or a griddle, pour a ladle of batter, and spread it in a circular motion to form a thin crepe. Drizzle a little oil around the edges and cook until golden brown and crispy. Flip and cook the other side for a minute if needed. Serve hot with coconut chutney and sambar.';
    } else if (selectedFood === 'Idli') {
        recipeText = 'Idli is a soft, steamed rice cake popular in South Indian cuisine. To prepare idli, soak 2 cups of rice and 1 cup of urad dal (split black gram) separately for 4-6 hours. Once soaked, grind the urad dal into a smooth paste, then grind the rice into a coarse paste, adding water as needed. Combine both pastes to form a batter, add salt, and let it ferment overnight or for 8-12 hours until it rises and becomes airy. After fermentation, stir the batter gently. Grease idli molds, pour the batter into the molds, and steam for 10-15 minutes until a toothpick inserted comes out clean. Remove the idlis from the molds and serve hot with chutney and sambar.';
    } else if (selectedFood === 'Sambar') {
        recipeText = 'Sambar is a flavorful South Indian lentil stew made with toor dal (split pigeon peas) and a variety of vegetables. To prepare, first, cook 1 cup of toor dal in a pressure cooker with 2-3 cups of water until soft, then mash it well. In a pan, heat oil and sauté mustard seeds, curry leaves, dried red chilies, and asafoetida. Add chopped onions, tomatoes, and vegetables like carrots, drumsticks, and eggplant, and cook for a few minutes. Add tamarind pulp, 1-2 tablespoons of sambar powder, salt, and water. Let it simmer until the vegetables are tender. Finally, mix in the mashed dal, bring it to a boil, and adjust the seasoning. Garnish with fresh coriander leaves and serve hot with rice, idli, or dosa.';
       
    } else if (selectedFood === 'Butter Chicken') {
        recipeText = 'Butter Chicken, also known as Murgh Makhani, is a rich and creamy North Indian dish. To prepare, first marinate 500g of boneless chicken in a mixture of yogurt, 1 tablespoon ginger-garlic paste, 1 tablespoon red chili powder, 1 teaspoon turmeric, and salt. Let it sit for at least 1 hour. In a hot pan, grill the marinated chicken until slightly charred, then set it aside. In the same pan, heat butter and sauté chopped onions, ginger, garlic, and green chilies until golden. Add 2-3 chopped tomatoes and cook until soft. Blend this mixture into a smooth puree. Return it to the pan, add 1 tablespoon of garam masala, 1 tablespoon of cumin powder, and 1 tablespoon of red chili powder. Pour in cream and a little water to create a thick sauce. Add the grilled chicken pieces, mix well, and simmer for 10 minutes. Garnish with fresh cream and coriander leaves, and serve hot with naan or rice.';
        
    } else if (selectedFood === 'Palak Paneer') {
        recipeText = 'Palak Paneer is a popular North Indian dish made with spinach (palak) and paneer (Indian cottage cheese). To prepare, start by blanching a bunch of spinach leaves in boiling water for 2-3 minutes, then transfer them to ice water to retain their vibrant green color. Blend the spinach into a smooth puree and set aside. In a pan, heat oil and sauté cumin seeds, chopped onions, ginger, garlic, and green chilies until golden. Add chopped tomatoes and cook until soft. Stir in 1 teaspoon of turmeric, 1 teaspoon of cumin powder, and 1 teaspoon of garam masala. Add the spinach puree and cook for a few minutes. Cube 200g of paneer and lightly fry or add it directly into the spinach gravy. Stir gently and cook for another 5 minutes, adjusting salt and consistency as needed. Finish with a splash of cream for richness. Serve hot with roti, naan, or rice.';
       
    } else if (selectedFood === 'Chole') {
        recipeText = 'Chole, also known as Chana Masala, is a flavorful North Indian dish made with chickpeas. To prepare, soak 1 cup of dried chickpeas overnight, then pressure cook them with water until tender. In a pan, heat oil and sauté cumin seeds, chopped onions, ginger, and garlic until golden brown. Add chopped tomatoes and cook until soft. Stir in 1 tablespoon of chole masala, 1 teaspoon of cumin powder, 1 teaspoon of coriander powder, 1/2 teaspoon of turmeric, and red chili powder. Cook the spices for a few minutes, then add the cooked chickpeas along with their cooking water. Simmer the mixture, mashing a few chickpeas to thicken the gravy. Add salt to taste and a squeeze of lemon juice for extra flavor. Garnish with fresh coriander and serve hot with bhature, puri, or rice.';
        
    } else if (selectedFood === 'Rasgulla') {
        recipeText = 'Rasgulla is a famous Bengali sweet made from soft, spongy balls of chenna (Indian cottage cheese) soaked in sugar syrup. To prepare, begin by boiling 1 liter of milk. Once it starts boiling, add 2 tablespoons of lemon juice or vinegar to curdle the milk. Strain the curdled milk (chenna) through a muslin cloth and rinse it under cold water to remove the lemony taste. Hang the cloth for about 30 minutes to drain excess water. Knead the chenna until smooth and soft, then shape it into small, smooth balls. In a separate pot, prepare sugar syrup by boiling 1 cup of sugar with 4 cups of water. Once boiling, gently drop the chenna balls into the syrup and cook covered on medium heat for 15-20 minutes, allowing the balls to double in size. Let the rasgullas cool in the syrup and serve chilled.';
       
    } else if (selectedFood === 'Fish Curry') {
        recipeText = 'Bengali Fish Curry, also known as Macher Jhol, is a flavorful and aromatic dish. To prepare, marinate 500g of fish (such as Rohu or Catla) with turmeric and salt, then lightly fry the pieces in mustard oil until golden. In the same pan, heat more mustard oil and add panch phoron (a Bengali five-spice blend), followed by sliced onions, ginger, and garlic. Sauté until golden, then add chopped tomatoes and cook until soft. Add turmeric, cumin, coriander powder, and red chili powder, along with some water to create a gravy. Simmer the gravy for 10 minutes, then add the fried fish pieces and let them cook in the sauce for another 10 minutes until tender. Garnish with fresh coriander and serve hot with steamed rice.';
        
    } else if (selectedFood === 'Mishti Doi') {
        recipeText = 'Mishti Doi is a traditional Bengali sweetened yogurt dessert that is creamy and delicious. To prepare, start by boiling 1 liter of full-fat milk and simmer it until it reduces to about half its original volume, stirring frequently to prevent burning. Once thickened, add 100g of sugar and mix until dissolved. Allow the mixture to cool to a warm temperature. In a separate bowl, take 2-3 tablespoons of plain yogurt (with live cultures) and whisk it until smooth. Gradually mix the warm milk into the yogurt, stirring gently to combine. Pour the mixture into earthen pots or bowls and cover them with a lid or cloth. Let the pots sit in a warm place for 6-8 hours to ferment until set. Once set, refrigerate the Mishti Doi for a few hours before serving. It can be garnished with a sprinkle of grated pistachios or almonds for added texture and flavor. Enjoy this delightful dessert chilled!';
        
    } else {
        recipeText = 'Please select a food item to see the recipe.';
    }

    recipeOutput.innerText = recipeText;
    
}
